server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
        - id: agent-service
          uri: lb://AGENT-SERVICE
          predicates:
            - Path=/api/agents/**
          filters:
            - RewritePath=/api/agents/(?<segment>.*), /$\{segment}
        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/api/properties/**
          filters:
            - RewritePath=/api/properties/(?<segment>.*), /$\{segment}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: users
        url: /api/users/v3/api-docs
      - name: agents
        url: /api/agents/v3/api-docs
      - name: properties
        url: /api/properties/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info
